export * from './basicErrorController.service';
import { BasicErrorControllerService } from './basicErrorController.service';
export * from './cotizacionesController.service';
import { CotizacionesControllerService } from './cotizacionesController.service';
export * from './emailController.service';
import { EmailControllerService } from './emailController.service';
export * from './garantiasController.service';
import { GarantiasControllerService } from './garantiasController.service';
export * from './nominaEmpleadosController.service';
import { NominaEmpleadosControllerService } from './nominaEmpleadosController.service';
export * from './ordenReparacionController.service';
import { OrdenReparacionControllerService } from './ordenReparacionController.service';
export * from './reclamoController.service';
import { ReclamoControllerService } from './reclamoController.service';
export * from './reportesController.service';
import { ReportesControllerService } from './reportesController.service';
export * from './tallerController.service';
import { TallerControllerService } from './tallerController.service';
export const APIS = [BasicErrorControllerService, CotizacionesControllerService, EmailControllerService, GarantiasControllerService, NominaEmpleadosControllerService, OrdenReparacionControllerService, ReclamoControllerService, ReportesControllerService, TallerControllerService];
