/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TblComercializadora } from './tblComercializadora';

export interface TblConcesionaria { 
    comercializadora?: TblComercializadora;
    conCorreo?: string;
    conDireccion?: string;
    conFoto?: string;
    conNombre?: string;
    conTelefono?: string;
    idConcesionaria?: number;
}