/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TblMarca } from './tblMarca';
import { TblPais } from './tblPais';
import { TblTipoCombustible } from './tblTipoCombustible';

export interface TblModelo { 
    idModelo?: number;
    marca?: TblMarca;
    modAnio?: number;
    modCilindraje?: string;
    modFoto?: string;
    modKmGarantia?: number;
    modNombre?: string;
    modPotencia?: string;
    paisOrigen?: TblPais;
    tipoCombustible?: TblTipoCombustible;
}