/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TblMarca } from './tblMarca';

export interface TblRespuestos { 
    idRepuesto?: number;
    marca?: TblMarca;
    repNombre?: string;
    repPrecio?: number;
}