/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TblConcesionaria } from './tblConcesionaria';
import { TblEjemplar } from './tblEjemplar';

export interface TblVehiculo { 
    concesionaria?: TblConcesionaria;
    ejemplar?: TblEjemplar;
    idVehiculo?: number;
    vehMatricula?: string;
    vehNumChasis?: string;
    vehNumMotor?: string;
    vehPrecio?: number;
    vehRAMV?: string;
}