/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Cliente } from './cliente';
import { Empleado } from './empleado';

export interface Cotizaciones { 
    cliente?: Cliente;
    cotDescripcion?: string;
    cotEstado?: number;
    cotFecha?: string;
    empleado?: Empleado;
    idConcesionaria?: number;
    idCotizacion?: number;
    idEjemplar?: number;
}