/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Empleado } from './empleado';
import { ManoObra } from './manoObra';
import { OrdenReparacion } from './ordenReparacion';
import { Repuestos } from './repuestos';

export interface InformeProformaReparacion { 
    empleado?: Empleado;
    manoDeObraList?: Array<ManoObra>;
    ordenReparacion?: OrdenReparacion;
    prDetalle?: string;
    prEstado?: number;
    prFecha?: string;
    prSubTotalManoObra?: number;
    prSubTotalRepuestos?: number;
    repuestosList?: Array<Repuestos>;
}