/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Empleado } from './empleado';
import { InformeReparacionComercializadora } from './informeReparacionComercializadora';
import { ManoObra } from './manoObra';
import { SolicitudRepuestos } from './solicitudRepuestos';

export interface InformeReparacionTaller { 
    empleado?: Empleado;
    informeReparacionComercializadora?: InformeReparacionComercializadora;
    ireDescripcion?: string;
    ireEstado?: number;
    ireFecha?: string;
    manoObraList?: Array<ManoObra>;
    solicitudRepuestos?: Array<SolicitudRepuestos>;
}