/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Empleado } from './empleado';

export interface InformeReparacionComercializadora { 
    empleadoActualizaInformeComercializadora?: Empleado;
    empleadoCreaInformeComercializadora?: Empleado;
    idFacturacionApiSql?: number;
    ircDescripcion?: string;
    ircEstado?: number;
    ircFecha?: string;
    ircGarantia?: number;
}