export * from './basicErrorController.service';
import { BasicErrorControllerService } from './basicErrorController.service';
export * from './clienteController.service';
import { ClienteControllerService } from './clienteController.service';
export * from './comercializadoraController.service';
import { ComercializadoraControllerService } from './comercializadoraController.service';
export * from './concesionariaController.service';
import { ConcesionariaControllerService } from './concesionariaController.service';
export * from './empeladoController.service';
import { EmpeladoControllerService } from './empeladoController.service';
export * from './facturaReparacionController.service';
import { FacturaReparacionControllerService } from './facturaReparacionController.service';
export * from './facturaVentaController.service';
import { FacturaVentaControllerService } from './facturaVentaController.service';
export * from './repuestoController.service';
import { RepuestoControllerService } from './repuestoController.service';
export * from './vehiculoController.service';
import { VehiculoControllerService } from './vehiculoController.service';
export const APIS = [BasicErrorControllerService, ClienteControllerService, ComercializadoraControllerService, ConcesionariaControllerService, EmpeladoControllerService, FacturaReparacionControllerService, FacturaVentaControllerService, RepuestoControllerService, VehiculoControllerService];
